@bot.command(name='joke')
async def random_joke(ctx):
    jokes = [
    "Why don't oysters donate to charity?\nBecause they are shellfish!",
    "Why did the football coach shake the vending machine?\nBecause he wanted his quarterback!",
    "Why don't oysters donate to charity?\nBecause they are shellfish!",
    "Why did the football coach shake the vending machine?\nBecause he wanted his quarterback!",
    "Why did the golfer bring two pairs of pants?\nIn case he got a hole in one!",
    "Why couldn't the bicycle stand up by itself?\nIt was two-tired!",
    "What did one DNA strand say to the other DNA strand?\nDo these genes make me look fat?",
    "Why did the politician bring a ladder to the election?\nBecause they wanted to climb the polls!",
    "Why did the scarecrow become a politician?\nBecause they was outstanding in their field!",
    "What do you call a group of politicians arguing?\nA filibuster!",
    "Why was the math book sad?\nBecause it had too many problems!",
    "Why don't politicians go on vacation?\nBecause they don't want to campaign!",
    "Why don't scientists trust atoms?\nBecause they make up everything!",
    "Why did the scarecrow win an award?\nBecause he was outstanding in his field!",
    "I asked the librarian if she had any books on paranoia.\nShe whispered, 'They're right behind you!'",
    "Why don't skeletons fight each other?\nThey don't have the guts!",
    "What did one wall say to the other wall?\nI'll meet you at the corner!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the chicken go to the seance? To talk to the other side!",
    "Why did the tomato turn to the mushroom for advice? Because he was a fungi!",
    "Why did the man put his money in the blender? Because he wanted to make some liquid assets!",
    "Why did the dog sit in the shade? Because he didn't want to be a hot dog!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "Why was the math book sad? Because it had too many problems!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the bicycle fall over? It was two-tired!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the chicken go to the seance? To talk to the other side!",
    "Why did the tomato turn to the mushroom for advice? Because he was a fungi!",
    "Why did the man put his money in the blender? Because he wanted to make some liquid assets!",
    "Why did the dog sit in the shade? Because he didn't want to be a hot dog!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "Why was the math book sad? Because it had too many problems!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the bicycle fall over? It was two-tired!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why did the chicken go to the seance? To talk to the other side!",
    "Why did the tomato turn to the mushroom for advice? Because he was a fungi!",
    "Why did the man put his money in the blender? Because he wanted to make some liquid assets!",
    "Why did the dog sit in the shade? Because he didn't want to be a hot dog!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "Why was the math book sad? Because it had too many problems!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the bicycle fall over? It was two-tired!",
    "Why did the computer go to art school? To become a pixel artist!",
    "Why did the man get hit by a car? Because he wasn't used to taking directions from a woman!",
    "Why did the woman bring a ladder to the bar? She heard the drinks were on the house, just like her!",
    "Why don't men need more than one bookmark? Because their attention span is as short as their temper!",
    "Why did the woman go to space? To escape the nagging and prove that even without a man, she could reach the stars!",
    "Why don't scientists trust atoms? Because they make up everything, just like sports stars make up excuses!",
    "Why was Cinderella such a poor basketball player? She always choked under pressure, just like her fairy godmother!",
    "Why did the baseball team hire a baker? Because they needed someone who could handle dough, just like their players!",
    "Why did the golfer bring two pairs of pants? In case he shanked his shot and wanted to hide his embarrassment!",
    "Why don't politicians play hide and seek? Because they're too busy hiding their corruption!",
    "Why was the math book sad? Because it had too many 'X' to solve in political equations, just like their promises!",
    "Why did the politician get kicked out of the bakery? Because he couldn't stop taking a slice of the profits!",
    "Why did the politician become a gardener? He wanted to plant some roots in the community and grow his influence!",
    "Why did the Buddhist refuse anesthesia during surgery? He wanted to suffer, just like his beliefs!",
    "Why don't scientists trust atoms? Because they make up everything, just like religious arguments make up for lack of evidence!",
    "Why did the preacher bring a ladder to church? He wanted to climb the hierarchy and maintain his godly power!",
    "Why did the priest go to art school? He wanted to paint holy pictures and cover up his unholy deeds!",
    "Why did the scarecrow become a successful business consultant? Because he had a brain full of straw, just like most executives!",
    "Why did the banker switch to gardening? He wanted to plant illegal money in offshore accounts!",
    "Why did the businessman bring a ladder to the office? He wanted to climb over his rivals and reach the top!",
    "Why did the entrepreneur start a bakery? Because he kneaded dough and wanted to rise to the occasion of bankruptcy!",
    "Why did the scientist get kicked out of the party? Because he couldn't stop talking about the time he dissected a cat!",
    "Why don't scientists trust atoms? Because they make up everything, just like their fabricated research findings!",
    "Why did the physicist bring a ladder to the lab? He wanted to reach new heights of irrationality in his experiments!",
    "Why did the biologist become a stand-up comedian? Because he needed to make jokes to compensate for his lack of social skills!",
    "What do you call a man who can't make decisions? A politician!",
    "What's the difference between a snowman and a snowwoman? Snowballs!",
    "What do you call a woman who has one leg shorter than the other? Eileen!",
    "What do you call a man who lost all of his intelligence? A tourist!",
    "What did the ocean say to the beach? Nothing, it just waved!",
    "What did one wall say to the other wall? I'll meet you at the corner!",
    "What do you call fake spaghetti? An impasta!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
    "What's the difference between a snowman and a snowwoman? Snowballs!",
    "What do you call a woman who has one leg shorter than the other? Eileen!",
    "What do you call a man who lost all of his intelligence? A tourist!",
    "What did one hat say to the other hat? You stay here, I'll go on ahead!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did the traffic light say to the car? Don't look, I'm about to change!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What's the difference between a hippo and a zippo? One is heavy, the other is a little lighter!",
    "What do you call a fish wearing a crown? King Neptune!",
    "What do you call a bear with no teeth? A gummy bear!",
    "What did the grape say when it got stepped on? Nothing, it just let out a little wine!",
    "How do you make a tissue dance? You put a little boogie in it!",
    "How does a penguin build its house? Igloos it together!",
    "How do you organize a space party? You planet!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "How does a train eat? It goes chew, chew!",
    "How do you make a lemon drop? Just let it fall!",
    "How do you talk to a giant? Use big words!",
    "How did the computer catch a cold? It left its Windows open!",
    "How do you catch a runaway dog? Hide behind a tree and make a sound like a stick!",
    "How do you find Will Smith in the snow? Look for the fresh prints!",
    "How do you organize an outer space party? You planet!",
    "How do you make a tissue dance? You put a little boogie in it!",
    "How does a penguin build its house? Igloos it together!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "How does a train eat? It goes chew, chew!",
    "How do you make a lemon drop? Just let it fall!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "What did the traffic light say to the car? Don't look, I'm about to change!",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus!",
    "What's the difference between a hippo and a zippo? One is heavy, the other is a little lighter!",
    "What do you call a fish wearing a crown? King Neptune!",
    "Where do ghosts go for vacation? Mali-boo!",
    "When do you know it's time to go to the dentist? When it's tooth-hurty!",
    "Where do cows go on Friday nights? To the moo-vies!",
    "When is a door not a door? When it's ajar!",
    "Where do snowmen keep their money? In a snow bank!",
    "When do astronauts eat? At launch time!",
    "Where did the computer go to dance? To the disc-o!",
    "When is a car not a car? When it turns into a driveway!",
    "Where do pencils go on vacation? Pencil-vania!",
    "When is the best time to go to the dentist? Tooth-hurty!",
    "Where did the sheep go on vacation? The Baa-hamas!",
    "When do birds fly south? When it gets too cold to walk!",
    "Where did the music teacher leave her keys? In the piano!",
    "When is the moon the heaviest? When it's full!",
    "Where do fish sleep at night? In a riverbed!",
    "When do you go at red and stop at green? When you're eating a watermelon!",
    "Where do basketball players go to dance? The basketball!",
    "When did the math book look sad? When it had too many problems!",
    "Where do ghosts go swimming? The Dead Sea!",
    "When do you go to a party in space? When you planet!",
    "Where did the dog go when it lost its tail? To the retail store!",
    "When do you go to a vegetable party? When you can't beet 'em, join 'em!",
    "Where did the sun go when it got tired? To bed, because it needed a light rest!",
    "When do clocks go on a diet? When they want to watch their waistlines!",
    "Where did the math book go to have fun? To the graph-ics!",
    "When do you know it's raining cats and dogs? When you step in a poodle!",
    "Where did the basketball player go to eat? Dunkin' Donuts!",
    "When do you go to a seafood disco? When you want to do the shrimp!",
    "Where did the bee go to the gym? To the hive and five!",
    "When did the tomato turn red? When it saw the salad dressing!",
    "Where do you go to learn about pancakes? To a waffle house!",
    "When do you go to a stadium to eat? When you're hungry for a home run!",
    "Where did the magician go to eat? Abra-Kebabra!",
    "When do you go to a fancy restaurant in space? When you want to try the Milky Way steak!",
    "Where did the fisherman go to get a new pole? To the tackle shop!",
    "When do you go to a circus to eat? When you want to have a lion's share of food!",
    "Where did the bee go to the barber? To a buzz cut!",
    "When do you go to a haunted house for dinner? When you're in the mood for a spook-tacular meal!",
    "Where did the cat go when it lost its tail? To the retail store!",
    "When do you go to a bakery in space? When you want to eat some cosmic rolls!",
    "Where did the dog go to have fun? To the bark park!",
    "What does a cloud wear under its coat? Thunderwear!",
    "What does a bee wear to the beach? Sunscreen!",
    "What does a robot do when it gets a cut? It downloads a bandage!",
    "What does a computer do when it's cold? It puts on a screensaver!",
    "What does a lamp say to a light bulb? 'You light up my life!'",
    "What does a mountain climber use to brush their teeth? Crest!",
    "What does a painter do when they're cold? They grab another coat!",
    "What do you do when you see a space invader? You pixelate them!",
    "What do you do when you see a bear? Play dead, but don't forget to press 'respawn'!",
    "What do you do when your car battery dies? Give it CPR (Charge, Push, Revive)!",
    "What do you do when you see a fire? You make sure it's 'lit'!",
    "What do you do when you find a hidden treasure? You keep it under 'lock' and 'key'!",
    "What do you do when you see a sinking ship? Jump on board and start a band!",
    "What do you do when a vampire bites you? You give them a coffin drop!",
    "What do you do when you find a lost key? You unlock new possibilities!",
    "What do you do when you see a math problem? You 'solve' it!",
    "What do you do when you see a spider? You let it spin its web of creativity!",
    "What do you do when you find a hole in your sock? You mend the 'sole'!",
    "What do you do when you see a fallen tree? You turn it into a 'logging' opportunity!",
    "What do you get when you cross a cat and a lemon? A sourpuss!",
    "What do you get when you cross a snowman and a vampire? A frostbite with a bite!",
    "What do you get when you cross a mouse and a frog? A jumpin' rodent!",
    "What do you get when you cross a pencil and a radio? Stationary waves!",
    "What do you get when you cross a ghost and a bee? A boo-bee!",
    "What do you get when you cross a kangaroo and a snake? A jump rope!",
    "What do you get when you cross a turtle and a porcupine? A slowpoke!",
    "What do you get when you cross a squirrel and a cactus? A prickly nut!",
    "What do you get when you cross a cat and a dog? A conflicted animal!",
    "What do you get when you cross a vampire and a snowman? A frosty bite!",
    "What do you get when you cross a clown and a vampire? A joker with bite marks!",
    "What do you get when you cross a bee and a mermaid? A comb with scales!",
    "What do you get when you cross a dinosaur and a spider? A web-footed creature!",
    "What do you get when you cross a gorilla and a computer? A banana that can program!",
    "What do you get when you cross a penguin and a parrot? A bird that talks in tuxedo!",
    "What do you get when you cross a robot and a tree? A mechanical sapling!",
    "What do you get when you cross a chicken and a cow? Two pieces of fried chicken and a milkshake!",
    "What do you get when you cross a shark and a cow? I have no idea, but I wouldn't try milking it!",
    "What do you get when you cross a giraffe and a squirrel? A long-legged rodent with a good view!",
    "What do you get when you cross a snail and a turtle? A slow and slimy racer!",
    "What do you get when you cross a snowman and a volcano? A meltdown on a cold day!",
    "What do you get when you cross a pirate and a snowman? A frosty buccaneer with a peg leg!",
    "What do you get when you cross a vampire and a pirate? A bloodthirsty swashbuckler!",
    "What do you get when you cross a ninja and a robot? An invisible metal warrior!",
    "What do you get when you cross a dinosaur and a detective? A T-Rex on the case!",
    "How many programmers does it take to change a light bulb? None, that's a hardware issue!",
    "How many cats does it take to make a movie? Just one, the rest are all copycats!",
    "How many tickles does it take to make an octopus laugh? Ten-tickles!",
    "How many ears does Captain Kirk have? Three: the left ear, the right ear, and the final frontier!",
    "How many books can you fit in an empty backpack? It depends on how you chapter them!",
    "How many apples grow on a tree? All of them!",
    "How many mathematicians does it take to screw in a light bulb? One, they just have to find the right angle!",
    "How many programmers does it take to kill a bug? None, it's a feature!",
    "How many tickles does it take to tickle an elephant? Too many, they have thick skin!",
    "How many witches does it take to change a light bulb? It depends on what you want to change it into!",
    "How many tennis players does it take to change a light bulb? None, they play during the day!",
    "How many software engineers does it take to change a light bulb? None, it's a hardware problem!",
    "How many psychologists does it take to change a light bulb? One, but the light bulb has to want to change!",
    "How many vegetarians does it take to screw in a light bulb? I don't know, but where do they get their protein?",
    "How many therapists does it take to change a light bulb? Just one, but the light bulb has to really want to change!",
    "How many Dragon Ball Z characters does it take to screw in a light bulb? Just one, but it'll take four episodes!",
    "How many actors does it take to change a light bulb? Only one, but they'll need three auditions and a callback!",
    "How many plumbers does it take to change a light bulb? None, that's an electrician's job!",
    "How many hipsters does it take to screw in a light bulb? Oh, you probably haven't heard of it, it's a really obscure number!",
    "How many drummers does it take to change a light bulb? Just one, but they'll need three drumsticks and a backup bulb!",
            
    ]
    joke = random.choice(jokes)
    await ctx.send(joke)
